name: Lenstack PROD Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Build api application
        working-directory: api
        run: |
          npm install
          npm run build

      - name: Build client application
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Copy Dependencies to build
        run: |
          cp -r api/package.json api/build

      - name: Move API build output to server dist directory
        run: |
          mv api/build dist

      - name: Move client build output to server dist directory
        run: |
          mv client/out dist/client

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Cleanup
        run: |
          cd .vercel/output/functions/dist/handler.js.func/dist
          npm uninstall @openzeppelin/contracts @types/express @types/node nodemon typescript @types/cors @types/jsonwebtoken @types/nodemailer concurrently

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
